### PR TITLE
Patch for nuspec namespace versions

### PR DESCRIPTION
**Pull request by NightOwl888**
This is a patch for #27. Fix for `Get-NuGetPackageMetadata` function so it will function with either of these namespaces:

```
http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd
```

or 

```
http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd
```

The logic was also changed a bit so more namespaces versions can be added easily to the `$ns` hash table, and they will be attempted in order from first to last.

I have tested locally with one NuGet packages of each namespace and can confirm it will work with either one now.

### CODE REVIEW

**Comment by onovotny** [comment]
I don't think you want to hard code the XML namespaces. You'll never keep up. Just take the root namespace dynamically

**Comment by NightOwl888** [comment]
Thanks. Come to think of it, I used this approach in another place, which I should do here as well.

```
$xml = [xml](Get-Content $tempFilePath)
$package.Name= ([string]$xml.package.metadata.id).Trim()
$package.Version = ([string]$xml.package.metadata.version).Trim()
```

**Comment by NightOwl888** [comment]
Unfortunately, I don't have a way to update the package, but I will fix the PR so this isn't dependent upon the `.nuspec` schema version.

**Comment by renevanosnabrugge** [comment]
I Will merge after my holidays

Verstuurd vanaf mijn iPhone

Op 25 jul. 2019 om 20:25 heeft Shad Storhaug <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


This is a patch for #27<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frenevanosnabrugge%2Fvsts-promotepackage-task%2Fissues%2F27&data=02%7C01%7C%7Cd82d28c27a0545acb20708d7112d73ff%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636996759221270339&sdata=qmHJvaH47Aq4lxoefc9dHNZIzffXELf1huCUOh7tt4k%3D&reserved=0>. Fix for Get-NuGetPackageMetadata function so it will function with either of these namespaces:

http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd


or

http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd


The logic was also changed a bit so more namespaces versions can be added easily to the $ns hash table, and they will be attempted in order from first to last.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/renevanosnabrugge/vsts-promotepackage-task/pull/28<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frenevanosnabrugge%2Fvsts-promotepackage-task%2Fpull%2F28&data=02%7C01%7C%7Cd82d28c27a0545acb20708d7112d73ff%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636996759221290354&sdata=hOZ754EQq4L9nTXJlszTyjdL2EiKw4E36ZQ3jQ7DkWA%3D&reserved=0>

Commit Summary

  *   Patched nuspec XML namespaces, as there are at least 2 in use, and made it possible to add additional namespaces without changing logic

File Changes

  *   M vsts-promotepackage-task/vsts-promotepackage-task.ps1<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frenevanosnabrugge%2Fvsts-promotepackage-task%2Fpull%2F28%2Ffiles%23diff-0&data=02%7C01%7C%7Cd82d28c27a0545acb20708d7112d73ff%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636996759221310370&sdata=%2BtBoFxgDGd4tRLS842k4xRIy4EyfrU4uKiC3ER21Jnk%3D&reserved=0> (15)

Patch Links:

  *   https://github.com/renevanosnabrugge/vsts-promotepackage-task/pull/28.patch<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frenevanosnabrugge%2Fvsts-promotepackage-task%2Fpull%2F28.patch&data=02%7C01%7C%7Cd82d28c27a0545acb20708d7112d73ff%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636996759221320381&sdata=f%2FDNKVVezvMI8DS9OOlURbqC6eyrkbCoZVt%2BSR5sVwM%3D&reserved=0>
  *   https://github.com/renevanosnabrugge/vsts-promotepackage-task/pull/28.diff<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frenevanosnabrugge%2Fvsts-promotepackage-task%2Fpull%2F28.diff&data=02%7C01%7C%7Cd82d28c27a0545acb20708d7112d73ff%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636996759221340397&sdata=xtR4o96%2F%2FvIoAT4cQ%2BM%2FhL%2FtFG%2FeylOkkvq51LiFVIA%3D&reserved=0>

**Comment by NightOwl888** [comment]
This PR has been superseded by #30.

**Pull request closed without merging**
