### PR TITLE
Support for on-prem TFS

### LINKED ISSUE #3: Remove hard-coded base URLs for VSTS
This task is listed as working for on-premise TFS.  However, looking at the code of the task, the base URLs are hard-coded to VSTS URLs.  Can this task be updated to function for on-premise?

### PR DESCRIPTION
**Pull request by dennismi**
This should fix #3.

Tested on an actual on-prem TFS (2017.2)

### CODE REVIEW

**Comment by dennismi** [comment]
@renevanosnabrugge had a chance to look it over?

**Comment by dennismi** [comment]
dang, not used to working with git and pull requests... you only need to merge the first two changes, deb6638 and bc996ab .. the last one has some major changes, made for my works "special" needs...

**Comment by MarkKharitonov** [comment]
Guys, what is the reason not to merge this PR? We need this.

**Comment by renevanosnabrugge** [comment]
On prem is hard to support for me because I do not have proper ways to test it. Since I have limited time I don’t want to release a buggy task.

I will try to take a look again. All URL’s changed to azure DevOps as well.

You can always fork and release a private task in your own marketplace of course !


Verstuurd vanaf mijn iPhone

Op 5 feb. 2019 om 21:55 heeft MarkKharitonov <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Guys, what is the reason not to merge this PR? We need this.

**Comment by renevanosnabrugge** [comment]
I installed a TFS 2018 and tested the extension with this pull request. It is not working because the endpoints in TFS, the REST API and authentication schemes differ. I will close the issue and will not fix for on-prem. because I cannot test it on the different versions.

**Comment by MarkKharitonov** [comment]
In that case could you explicitly mention it on the plugin page that it does not support on-premises TFS?

**Comment by renevanosnabrugge** [comment]
By default this is mentioned on the right side of the marketplace page (works with) but iT might be unclear

I Will update the page

Verstuurd vanaf mijn iPhone

Op 8 feb. 2019 om 01:18 heeft MarkKharitonov <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


In that case could you explicitly mention it on the plugin page that it does not support on-premises TFS?

**Pull request closed without merging**
